version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rvas-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    networks:
      - rvas-network
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

networks:
  rvas-network:
    driver: bridge
